name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcxx=10.0.0=1
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h3d69b6c_0
  - llvm-openmp=10.0.0=h28b9765_0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.18.1=py38h1f821a2_1
  - openssl=1.1.1g=h0b31af3_0
  - pip=20.0.2=py_2
  - python=3.8.2=hd5f0129_7_cpython
  - python_abi=3.8=1_cp38
  - readline=8.0=hcfe32e1_0
  - setuptools=46.1.3=py38h32f6830_0
  - sqlite=3.30.1=h93121df_0
  - tk=8.6.10=hbbe82c9_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h0b31af3_0
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/jenniferblanc/miniconda3/envs/test

